name: Build Debug APK

on:
  workflow_dispatch:

jobs:
  build-and-upload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Build debug APK
        run: ./gradlew :app:android:assembleDebug

      - name: Upload APK as artifact
        uses: actions/upload-artifact@v3
        with:
          name: app
          path: app/android/build/outputs/apk/debug/android-debug.apk
